### ISSUE TITLE
Stacking and CSS Display: Block

### ISSUE THREAD

**Issue by Teyler7** [matthewnitschke/ko-dropdown#1]
Hey there,
Love your knockout software as always :1st_place_medal:  I do have a suggestion that could further improve your work. This is what happens when 2 drop downs that are in the same area look like when they are both active.
![2017-01-24_10h34_14](https://cloud.githubusercontent.com/assets/11841273/22258947/a923c7b2-e220-11e6-96a8-520c5e75516e.png)
I don't know if the most simple way to fix this is if the active drop down is clicked away from that it becomes active or what. 

There is also a really really simple CSS hierarchy issue that I had with out style sheet because our CSS was setting the display to hidden since there is no display property set for the dropdown class in ko-dropdown. I think it would be as simple as adding a **Display: Block** to the dropdown class like so:
```css
.dropdown ul {
    display: block;
    list-style: none;
    padding: 0;
    margin: 0;
    position: absolute;
    top: 1.7em;
    left: 0;
    z-index: 5;
    border-top: 1px solid #ccc;
    width: 100%;
    color: #f08800;
    background-color: #e5e5e8; }
```
